### ISSUE TITLE
Fix meson config for required version of `setuptools_scm` dependency

### ISSUE THREAD

**Issue by truth-quark** [OpenDataCubePipelines/ard-pipeline#54]
Following the `README ` build steps for an NCI `wagl` setup can result in `setuptools_scm` dependency failing to install. If _too new_ a version of `setuptools_scm` is installed, this has been known to cause a subtle build system breakage, apparent when running `./deployment/check-environment.sh`, such as:

```BASH
$ ./deployment/check-environment.sh
Checking environment...
Trying rasterio... ✅ 1.3.9
Trying luigi... ✅ 3.5.0
Trying wagl... ❌
        No module named 'wagl._version'
Attempting load of fortran-based modules... Traceback (most recent call last):
  File "<stdin>", line 29, in <module>
  File "/g/data/u46/users/bpd578/projects/ard-pipeline/wagl/__init__.py", line 5, in <module>
    from ._version import __version__
ModuleNotFoundError: No module named 'wagl._version'
```
The version module is produced by `setuptools_scm`.

The `meson` config needs adjustment to ensure the required version of `setuptools_scm` is installed.

**Comment by uchchwhash** [comment]
@truth-quark is this fixed now? Can I close it?

**Comment by truth-quark** [comment]
> @truth-quark is this fixed now? Can I close it?

No, there's been no work on it.
